name: ci

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19'
        cache: 'npm'
    - run: npm ci
    - run: npx playwright install
    - run: npx playwright test --config=playwright-e2e-tests.config.ts --project='E2E testing with chromium'

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: single-spec-report
        path: e2e/report

    - name: Adding note
      if: always()
      run: |
        echo 'Open the index.html from the single-spec-report artifact to read the report.' >> $GITHUB_STEP_SUMMARY
        echo 'Drop .zip trace file into the [Playwright Trace Viewer](https://trace.playwright.dev/) to debug tests.' >> $GITHUB_STEP_SUMMARY
