name: single-run

on:
  workflow_dispatch:
    inputs:
      specPath:
        type: string
        required: true
        description: Write spec name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19'
        cache: 'npm'
    - run: npm ci
    - run: npx playwright install
    - run: npx playwright test ${{ github.event.inputs.specPath }} --config=playwright-e2e-tests.config.ts --project='E2E testing with chromium'

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Adding note
      if: always()
      run: |
        echo 'Open the index.html from the single_run artifact to read the report.' >> $GITHUB_STEP_SUMMARY
        echo 'Drop .zip trace file into the [Playwright Trace Viewer](https://trace.playwright.dev/) to debug tests.' >> $GITHUB_STEP_SUMMARY
